### ISSUE TITLE
4v8m not found in raw directory. When processing go-bp dataset

### ISSUE THREAD

**Issue by yangzhang33** [a-r-j/ProteinWorkshop#96]
Hello, when running classification task on go-bp dataset, it gives an error:  
FileNotFoundError: 4v8m not found in raw directory. Are you sure it's downloaded and has the format pdb?

with the format=pdb(cause the mmtf doesn't work)

I checked the pdb site: it says for large graphs pdb file is not available
<img width="263" alt="截屏2024-07-23 14 42 09" src="https://github.com/user-attachments/assets/0ea35d81-3bff-44b6-811a-fe21eafe215e">

Is there any way to work around this?

**Comment by a-r-j** [comment]
Hi @yangzhang33, thanks for flagging. This is a little tricky. I'd suggest removing that example from the dataset for now. If you're keen to include it I think you can download the mmcif, extract the relevant chains and write them to a PDB file (i.e. using BioPandas). I don't think it's possible to get the structure in pdb format otherwise.
